language: go
go:
  - 1.13.x
install:
- go get golang.org/x/tools/cmd/goimports
services:
  - docker
env:
  global:
    - GO111MODULE=on
  matrix:
    - KONG_VERSION=1.2
    - KONG_VERSION=1.3
    - KONG_VERSION=1.4
